### PR TITLE
use multiapi instead of all-api-versions

### PR DESCRIPTION
**Pull request by leni-msft**
This PR is to align the autorest parameters with the one used in SDK Automation pipeline, i.e., use `--multiapi` instead of `--all-api-versions`. With `--multiapi` parameter, autorest reads the tags in readme.azureresourceschema.md, and generate schemas for each tag.

### CODE REVIEW

**Comment by leni-msft** [comment]
Here's related PR to fix readme.azureresourceschema.md: https://github.com/Azure/azure-rest-api-specs/pull/10615

**Comment by anthony-c-martin** [comment]
@leni-msft  your changes look good to me. Have you validated that they generate exactly the same set of schemas when you run `npm run generate-all`?

**Comment by leni-msft** [comment]
@anthony-c-martin I tried generate-single for several onboarded RPs, and the result are same. I will try generate-all, and update you further. Stay tuned. :)

**Comment by anthony-c-martin** [comment]
> @anthony-c-martin I tried generate-single for several onboarded RPs, and the result are same. I will try generate-all, and update you further. Stay tuned. :)

Thanks! You can probably also just kick off the pipelines [here](https://dev.azure.com/azure/azure-resource-manager-schemas/_build) on this branch to check this.

**Comment by leni-msft** [comment]
@anthony-c-martin Thanks for the information. The pipeline executed successfully. Here's draft PR to see the schema changes: https://github.com/Azure/azure-resource-manager-schemas/pull/1156/files/87abca78f5ab4d04f67d584885d7885f7ad5ddc2..97861662d0be9845d192c086f97755c26705680e I'll continue investigate the cause.

**Pull request closed without merging**
