### PR TITLE
Manually generate and add schema for Microsoft PlayFab RP

### PR DESCRIPTION
**Pull request by bhavyej**
# Adding Schema for Microsoft PlayFab RP

## Description
PlayFab is a new RP in Azure. PlayFab swagger is not yet checked-into the public api-specs repository since the API is behind AFEC. Template export is a requirement for private preview for this RP. This schema is generated from the swagger in the private api-specs repository, which is currently in use for the RP APIs.

## Schema Generator Output
```
> azure-schema-generator@1.0.0 generate-single C:\github\azure-resource-manager-schemas\generator
> ts-node cmd/generatesingle "playfab/resource-manager" "C:\github\azure-rest-api-specs-pr"

Using autogenlist config:
{
  "basePath": "playfab/resource-manager",
  "namespace": "Microsoft.PlayFab"
}
[C:\github\azure-resource-manager-schemas\generator] executing: C:\github\azure-resource-manager-schemas\generator/node_modules/.bin/autorest.cmd --version=3.0.6374 --use=@autorest/azureresourceschema@3.0.92 --azureresourceschema --output-folder=C:\Users\BHAVYE~1\AppData\Local\Temp\km6ecv04b3 --multiapi --pass-thru:subset-reducer C:\github\azure-rest-api-specs-pr\specification\playfab\resource-manager\readme.md
AutoRest code generation utility [cli version: 3.3.2; node: v12.18.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: 3.0.6374.

There is a new version of AutoRest available (3.4.2).
 > You can install the newer version with with npm install -g autorest@latest

   Loading AutoRest core      'C:\Users\bhavyejain\.autorest\@autorest_core@3.0.6374\node_modules\@autorest\core\dist' (3.0.6374)
   Loading AutoRest extension '@autorest/azureresourceschema' (3.0.92->3.0.92)
Processing batch task - {"tag":"schema-2021-09-07-preview"} .
[5.83 s] Generation Complete
================================================================================================================================
Filename: C:\github\azure-resource-manager-schemas\schemas\2021-09-07-preview\Microsoft.PlayFab.json
Provider Namespace: Microsoft.PlayFab
API Version: 2021-09-07-preview
Resource Types (Resource Group Scope):
- playerAccountPools
- titles
================================================================================================================================
```

### CODE REVIEW

**Comment by anthony-c-martin** [comment]
@bhavyej - we don't take contributions for private preview services; this repo is only for services which are publicly available (either public preview, or GA)

**Comment by bhavyej** [comment]
@anthony-c-martin oh, I see. Our RP got a requirement from the PMs that we need template export functionality in the private preview, hence I tried for the manual method. I'll get back to them with this information. Thanks a lot!

**Comment by anthony-c-martin** [comment]
Discussed offline - we're going to check this in for now, with the expectation that it'll be replaced by autogenerated schemas when the RP enters public preview.

**Comment by anthony-c-martin** [comment]
@bhavyej - I'm happy to sign off, but am not able to validate that export works as expected with your service. Could you try running through https://armwiki.azurewebsites.net/rp_onboarding/process/template_schemas.html#simulating-export-locally to confirm things look good? Once done, I'll be happy to merge this.

**Review by anthony-c-martin — APPROVED** [review]

**Pull request merged**
