### PR TITLE
Onboarding Microsoft.DeviceUpdate for autogeneration

### PR DESCRIPTION
**Pull request by abatishchev**
Per the instruction [here](https://github.com/Azure/azure-resource-manager-schemas/tree/master/generator#onboarding-to-the-autogeneration-pipeline).

```
npm run generate-single deviceupdate/resource-manager

> azure-schema-generator@1.0.0 generate-single D:\Projects\azure-resource-manager-schemas\generator
> ts-node cmd/generatesingle "deviceupdate/resource-manager"

[D:\Projects\azure-resource-manager-schemas\generator] executing: D:\Projects\azure-resource-manager-schemas\generator/node_modules/.bin/autorest.cmd --version=3.0.6374 --use=@autorest/azureresourceschema@3.0.92 --azureresourceschema --output-folder=c:\Temp\xwqrdg4ovpc --multiapi --pass-thru:subset-reducer D:\Projects\azure-rest-api-specs\specification\deviceupdate\resource-manager\readme.md
AutoRest code generation utility [cli version: 3.2.3; node: v14.17.1, max-memory: 4096 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\alexbat.REDMOND\.autorest\@autorest_core@3.0.6374\node_modules\@autorest\core\dist' (3.0.6374)
   Loading AutoRest extension '@autorest/azureresourceschema' (3.0.92->3.0.92)
Processing batch task - {"tag":"schema-2020-03-01-preview"} .
[8.26 s] Generation Complete
================================================================================================================================
Filename: D:\Projects\azure-resource-manager-schemas\schemas\2020-03-01-preview\Microsoft.DeviceUpdate.json
Provider Namespace: Microsoft.DeviceUpdate
API Version: 2020-03-01-preview
Resource Types (Resource Group Scope):
- accounts
- accounts/instances
================================================================================================================================
```

### CODE REVIEW

**Comment by abatishchev** [comment]
@anthony-c-martin the instruction mentions only [schemas/2019-04-01/deploymentTemplate.json](https://github.com/Azure/azure-resource-manager-schemas/blob/master/schemas/2019-04-01/deploymentTemplate.json). Does it mean older versions won't be update anymore?

[Here's](https://github.com/abatishchev/azure-resource-manager-schemas/commit/a8599744d4d7114f176254f7b4b43499b0f5b9dc) my another, older commit which updates other api versions too. Can you please explain if that's needed / possible, or not anymore?

**Review by anthony-c-martin — APPROVED** [review]
Thanks!

**Comment by abatishchev** [comment]
hi @anthony-c-martin, can you please come back to [this question](https://github.com/Azure/azure-resource-manager-schemas/pull/1772#issuecomment-864230416) for a moment:

>the instruction mentions only schemas/2019-04-01/deploymentTemplate.json. Does it mean the older versions won't be update anymore?

>Here's my another, older commit which updates other api versions as well. Can you please explain if that's needed / possible, or not anymore?

**Comment by anthony-c-martin** [comment]
> hi @anthony-c-martin, can you please come back to [this question](https://github.com/Azure/azure-resource-manager-schemas/pull/1772#issuecomment-864230416) for a moment:
> 
> > the instruction mentions only schemas/2019-04-01/deploymentTemplate.json. Does it mean the older versions won't be update anymore?
> 
> > Here's my another, older commit which updates other api versions as well. Can you please explain if that's needed / possible, or not anymore?

@abatishchev Sorry, I missed this earlier. It's not necessary to keep the old root schemas up to date any more - we have a note about this here: https://github.com/Azure/azure-resource-manager-schemas#submitting-a-pr

image

**Pull request merged**
