### PR TITLE
Add DNS resources for 2017-10-01 Microsoft.Network schema

### PR DESCRIPTION
**Pull request by nkindberg**
Adding DNS resources to 2017-10-01 Microsoft.Network schema.

No new resource types here - so no changes to deploymentTemplate files.

### CODE REVIEW

**Comment by TianoMS** [comment]
>     "dnsZones": {

this is new resource type, right?

---
Refers to: schemas/2017-10-01/Microsoft.Network.json:1330 in d70e47e. [](commit_id = d70e47e90109bb2cd1653d794b7e3e3c62e19b8e, deletion_comment = False)

**Comment by nkindberg** [comment]
@TianoMS dnsZones? No, dnsZones are an existing resource type. See 2017-09-01 schema for example: https://github.com/Azure/azure-resource-manager-schemas/blob/ad5c8c6eaac0cac6e2091d43f79759e804c3ceb6/schemas/2017-09-01/Microsoft.Network.json#L1344

**Comment by Tiano2017** [comment]
@nkindberg It's a new api-version so you'll need to add it to deploymentTemplate, otherwise customers won't be able to add a "dnsZones" with 2017-10-01 in their template.

**Comment by nkindberg** [comment]
@Tiano2017 gotcha, fixed

**Pull request merged**
