### PR TITLE
Update Service Fabric ARM schema

### PR DESCRIPTION
**Pull request by Tadimsky**
Using the [auto generator](https://github.com/Azure/azure-resource-manager-schemas#autogenerating-from-swagger) and fixing some of the tests.

Command used: ` npm run generate-single -- -BasePath servicefabric/resource-manager`

Current ARM schema is invalid, if you follow it you cannot deploy applications.

Command output:

```
================================================================================================================================
Filename: C:\Users\joschm\AppData\Local\Temp\schm_dbaeca21-4f23-4e45-a041-f6adf7836c5e\2016-09-01\Microsoft.ServiceFabric.json
Provider Namespace: Microsoft.ServiceFabric
API Version: 2016-09-01
Resource Types:
- Microsoft.ServiceFabric/clusters
Resource References:
- https://schema.management.azure.com/schemas/2016-09-01/Microsoft.ServiceFabric.json#/resourceDefinitions/clusters
================================================================================================================================
================================================================================================================================
Filename: C:\Users\joschm\AppData\Local\Temp\schm_dbaeca21-4f23-4e45-a041-f6adf7836c5e\2017-07-01-preview\Microsoft.ServiceFabric.json
Provider Namespace: Microsoft.ServiceFabric
API Version: 2017-07-01-preview
Resource Types:
- Microsoft.ServiceFabric/clusters
- Microsoft.ServiceFabric/clusters/applications
- Microsoft.ServiceFabric/clusters/applications/services
- Microsoft.ServiceFabric/clusters/applicationTypes
- Microsoft.ServiceFabric/clusters/applicationTypes/versions
Resource References:
- https://schema.management.azure.com/schemas/2017-07-01-preview/Microsoft.ServiceFabric.json#/resourceDefinitions/clusters
- https://schema.management.azure.com/schemas/2017-07-01-preview/Microsoft.ServiceFabric.json#/resourceDefinitions/clusters_applications
- https://schema.management.azure.com/schemas/2017-07-01-preview/Microsoft.ServiceFabric.json#/resourceDefinitions/clusters_applications_services
- https://schema.management.azure.com/schemas/2017-07-01-preview/Microsoft.ServiceFabric.json#/resourceDefinitions/clusters_applicationTypes
- https://schema.management.azure.com/schemas/2017-07-01-preview/Microsoft.ServiceFabric.json#/resourceDefinitions/clusters_applicationTypes_versions
================================================================================================================================
================================================================================================================================
Filename: C:\Users\joschm\AppData\Local\Temp\schm_dbaeca21-4f23-4e45-a041-f6adf7836c5e\2018-02-01\Microsoft.ServiceFabric.json
Provider Namespace: Microsoft.ServiceFabric
API Version: 2018-02-01
Resource Types:
- Microsoft.ServiceFabric/clusters
Resource References:
- https://schema.management.azure.com/schemas/2018-02-01/Microsoft.ServiceFabric.json#/resourceDefinitions/clusters
================================================================================================================================
================================================================================================================================
Filename: C:\Users\joschm\AppData\Local\Temp\schm_dbaeca21-4f23-4e45-a041-f6adf7836c5e\2019-03-01-preview\Microsoft.ServiceFabric.json
Provider Namespace: Microsoft.ServiceFabric
API Version: 2019-03-01-preview
Resource Types:
- Microsoft.ServiceFabric/clusters
- Microsoft.ServiceFabric/clusters/applications
- Microsoft.ServiceFabric/clusters/applications/services
- Microsoft.ServiceFabric/clusters/applicationTypes
- Microsoft.ServiceFabric/clusters/applicationTypes/versions
Resource References:
- https://schema.management.azure.com/schemas/2019-03-01-preview/Microsoft.ServiceFabric.json#/resourceDefinitions/clusters
- https://schema.management.azure.com/schemas/2019-03-01-preview/Microsoft.ServiceFabric.json#/resourceDefinitions/clusters_applications
- https://schema.management.azure.com/schemas/2019-03-01-preview/Microsoft.ServiceFabric.json#/resourceDefinitions/clusters_applications_services
- https://schema.management.azure.com/schemas/2019-03-01-preview/Microsoft.ServiceFabric.json#/resourceDefinitions/clusters_applicationTypes
- https://schema.management.azure.com/schemas/2019-03-01-preview/Microsoft.ServiceFabric.json#/resourceDefinitions/clusters_applicationTypes_versions
================================================================================================================================
```

### CODE REVIEW

**Comment by Tadimsky** [comment]
I'm getting the following error that I don't know how to resolve:

```
{
      -    "message": "Matches multiple schemas when only one must validate."
      -    "range": {
      -      "end": {
      -        "character": 5
      -        "line": 1393
      -      }
      -      "start": {
      -        "character": 4
      -        "line": 1393
      -      }
      -    }
      -    "severity": 2
      -  }
```

Any ideas?

**Comment by anthony-c-martin** [comment]
> Any ideas?

The 2019-04-01/deploymentTemplate.json schema also includes references to autogeneratedResources.json, so the test is seeing duplicate references. If the files in `/schemas` were fully auto-generated (i.e. you didn't make any manual changes after running the tool), then you can just remove all references to `Microsoft.ServiceFabric` schemas from 2019-04-01/deploymentTemplate.json, and please also add the base path to the whitelist in `generator/scripts/constants.ps1`.

**Comment by Tadimsky** [comment]
@anthony-c-martin awesome, thanks very much for the pointers.
And so `2019-04-01` is the only schema that uses the autogenerated file? Does that mean we need to switch to this schema to get all the benefits?

**Comment by anthony-c-martin** [comment]
> @anthony-c-martin awesome, thanks very much for the pointers.
> And so `2019-04-01` is the only schema that uses the autogenerated file? Does that mean we need to switch to this schema to get all the benefits?

The older 2015-01-01 schema is still the current - at the moment we're manually adding autogenerated resources back into it. Because 2019-04-01 is more complete, it has a larger set of resources to process, which can cause performance problems for some IDEs. While we work this out, recommendation is to keep using 2015-01-01.

**Comment by Tadimsky** [comment]
@anthony-c-martin ok, makes sense.
Will 2015 contain these changes for Service Fabric? Or does that need the manual step you mentioned.

**Comment by anthony-c-martin** [comment]
> @anthony-c-martin ok, makes sense.
> Will 2015 contain these changes for Service Fabric? Or does that need the manual step you mentioned.

My apologies, I merged too soon - didn't notice you had also added a brand new api-version entry. Yes the new schema references will need to be added back into the older root schemas. I'll send out a PR for this.

**Comment by anthony-c-martin** [comment]
Created PR https://github.com/Azure/azure-resource-manager-schemas/pull/666 to backport new API version

**Comment by Tadimsky** [comment]
Ok, so without your new PR #666 it would have contained all the updates to the existing APIs but it would not have included the new one (`2019-03-01-preview`).

How long after these changes is the actual schema updated online on the `https://schema.management.azure.com` site?

**Comment by Tadimsky** [comment]
@anthony-c-martin how long does it take for these changes to actually be deployed?

**Pull request merged**
