### PR TITLE
Onboard compute for auto-generation 

### PR DESCRIPTION
**Pull request by grizzlytheodore**
Generation log:
```
> azure-schema-generator@1.0.0 generate-single /workspaces/azure-resource-manager-schemas/generator
> ts-node cmd/generatesingle "compute/resource-manager"

[/tmp/schm_azspc] executing: git fsck
[/tmp/schm_azspc] executing: git reset -q .
[/tmp/schm_azspc] executing: git checkout -q -- .
[/tmp/schm_azspc] executing: git clean -q -fd
[/tmp/schm_azspc] executing: git gc
[/tmp/schm_azspc] executing: git fetch -q
[/tmp/schm_azspc] executing: git checkout -q origin/main
Path compute/resource-manager has been disabled for generation:
{
  "basePath": "compute/resource-manager",
  "namespace": "Microsoft.ContainerService",
  "disabledForAutogen": true
}
Using autogenlist config:
{
  "basePath": "compute/resource-manager",
  "namespace": "Microsoft.Compute"
}
[/workspaces/azure-resource-manager-schemas/generator] executing: /workspaces/azure-resource-manager-schemas/generator/node_modules/.bin/autorest --version=3.0.6374 --use=@autorest/azureresourceschema@3.0.92 --azureresourceschema --output-folder=/tmp/0t8bz21o2tqd --multiapi --pass-thru:subset-reducer /tmp/schm_azspc/specification/compute/resource-manager/readme.md
AutoRest code generation utility [cli version: 3.3.2; node: v14.15.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: 3.0.6374.

There is a new version of AutoRest available (3.4.0).
 > You can install the newer version with with npm install -g autorest@latest

   Loading AutoRest core      '/home/codespace/.autorest/@autorest_core@3.0.6374/node_modules/@autorest/core/dist' (3.0.6374)
   Loading AutoRest extension '@autorest/azureresourceschema' (3.0.92->3.0.92)
Processing batch task - {"tag":"schema-2021-07-01"} .
Processing batch task - {"tag":"schema-2021-04-01"} .
Processing batch task - {"tag":"schema-2021-03-01"} .
Processing batch task - {"tag":"schema-2019-04-01"} .
Processing batch task - {"tag":"schema-2020-12-01"} .
Processing batch task - {"tag":"schema-2020-09-30"} .
Processing batch task - {"tag":"schema-2021-06-01-preview"} .
Processing batch task - {"tag":"schema-2019-12-01"} .
Processing batch task - {"tag":"schema-2020-06-01"} .
Processing batch task - {"tag":"schema-2020-10-01-preview"} .
Processing batch task - {"tag":"schema-2020-06-30"} .
Processing batch task - {"tag":"schema-2020-05-01"} .
Processing batch task - {"tag":"schema-2019-11-01"} .
Processing batch task - {"tag":"schema-2019-07-01"} .
Processing batch task - {"tag":"schema-2019-03-01"} .
Processing batch task - {"tag":"schema-2018-10-01"} .
Processing batch task - {"tag":"schema-2017-09-01"} .
Processing batch task - {"tag":"schema-2018-09-30"} .
Processing batch task - {"tag":"schema-2018-06-01"} .
Processing batch task - {"tag":"schema-2018-04-01"} .
Processing batch task - {"tag":"schema-2017-12-01"} .
Processing batch task - {"tag":"schema-2017-03-30"} .
Processing batch task - {"tag":"schema-2016-04-30-preview"} .
Processing batch task - {"tag":"schema-2016-03-30"} .
Processing batch task - {"tag":"schema-2015-06-15"} .
[799.05 s] Generation Complete
================================================================================================================================
Filename: /workspaces/azure-resource-manager-schemas/schemas/2015-06-15/Microsoft.Compute.json
Provider Namespace: Microsoft.Compute
API Version: 2015-06-15
Resource Types (Resource Group Scope):
- availabilitySets
- virtualMachines
- virtualMachineScaleSets
================================================================================================================================
================================================================================================================================
Filename: /workspaces/azure-resource-manager-schemas/schemas/2016-03-30/Microsoft.Compute.json
Provider Namespace: Microsoft.Compute
API Version: 2016-03-30
Resource Types (Resource Group Scope):
- availabilitySets
- virtualMachines
- virtualMachineScaleSets
================================================================================================================================
================================================================================================================================
Filename: /workspaces/azure-resource-manager-schemas/schemas/2016-04-30-preview/Microsoft.Compute.json
Provider Namespace: Microsoft.Compute
API Version: 2016-04-30-preview
Resource Types (Resource Group Scope):
- availabilitySets
- disks
- images
- snapshots
- virtualMachines
- virtualMachineScaleSets
================================================================================================================================
================================================================================================================================
Filename: /workspaces/azure-resource-manager-schemas/schemas/2017-03-30/Microsoft.Compute.json
Provider Namespace: Microsoft.Compute
API Version: 2017-03-30
Resource Types (Resource Group Scope):
- availabilitySets
- disks
- images
- snapshots
- virtualMachines
- virtualMachineScaleSets
================================================================================================================================
================================================================================================================================
Filename: /workspaces/azure-resource-manager-schemas/schemas/2017-12-01/Microsoft.Compute.json
Provider Namespace: Microsoft.Compute
API Version: 2017-12-01
Resource Types (Resource Group Scope):
- availabilitySets
- images
- virtualMachines
- virtualMachineScaleSets
- virtualMachineScaleSets/virtualmachines
================================================================================================================================
================================================================================================================================
Filename: /workspaces/azure-resource-manager-schemas/schemas/2018-04-01/Microsoft.Compute.json
Provider Namespace: Microsoft.Compute
API Version: 2018-04-01
Resource Types (Resource Group Scope):
- availabilitySets
- disks
- images
- proximityPlacementGroups
- snapshots
- virtualMachines
- virtualMachineScaleSets
- virtualMachineScaleSets/virtualmachines
================================================================================================================================
================================================================================================================================
Filename: /workspaces/azure-resource-manager-schemas/schemas/2018-06-01/Microsoft.Compute.json
Provider Namespace: Microsoft.Compute
API Version: 2018-06-01
Resource Types (Resource Group Scope):
- availabilitySets
- disks
- galleries
- galleries/images
- galleries/images/versions
- images
- proximityPlacementGroups
- snapshots
- virtualMachines
- virtualMachineScaleSets
- virtualMachineScaleSets/virtualmachines
================================================================================================================================
================================================================================================================================
Filename: /workspaces/azure-resource-manager-schemas/schemas/2018-09-30/Microsoft.Compute.json
Provider Namespace: Microsoft.Compute
API Version: 2018-09-30
Resource Types (Resource Group Scope):
- disks
- snapshots
================================================================================================================================
================================================================================================================================
Filename: /workspaces/azure-resource-manager-schemas/schemas/2018-10-01/Microsoft.Compute.json
Provider Namespace: Microsoft.Compute
API Version: 2018-10-01
Resource Types (Resource Group Scope):
- availabilitySets
- images
- proximityPlacementGroups
- virtualMachines
- virtualMachineScaleSets
- virtualMachineScaleSets/virtualmachines
================================================================================================================================
================================================================================================================================
Filename: /workspaces/azure-resource-manager-schemas/schemas/2019-03-01/Microsoft.Compute.json
Provider Namespace: Microsoft.Compute
API Version: 2019-03-01
Resource Types (Resource Group Scope):
- availabilitySets
- disks
- galleries
- galleries/applications
- galleries/applications/versions
- galleries/images
- galleries/images/versions
- hostGroups
- hostGroups/hosts
- images
- proximityPlacementGroups
- snapshots
- virtualMachines
- virtualMachineScaleSets
- virtualMachineScaleSets/virtualmachines
================================================================================================================================
================================================================================================================================
Filename: /workspaces/azure-resource-manager-schemas/schemas/2019-07-01/Microsoft.Compute.json
Provider Namespace: Microsoft.Compute
API Version: 2019-07-01
Resource Types (Resource Group Scope):
- availabilitySets
- diskEncryptionSets
- disks
- galleries
- galleries/applications
- galleries/applications/versions
- galleries/images
- galleries/images/versions
- hostGroups
- hostGroups/hosts
- images
- proximityPlacementGroups
- snapshots
- virtualMachines
- virtualMachineScaleSets
- virtualMachineScaleSets/virtualmachines
- virtualMachineScaleSets/virtualMachines/extensions
================================================================================================================================
================================================================================================================================
Filename: /workspaces/azure-resource-manager-schemas/schemas/2019-11-01/Microsoft.Compute.json
Provider Namespace: Microsoft.Compute
API Version: 2019-11-01
Resource Types (Resource Group Scope):
- diskEncryptionSets
- disks
- snapshots
================================================================================================================================
================================================================================================================================
Filename: /workspaces/azure-resource-manager-schemas/schemas/2019-12-01/Microsoft.Compute.json
Provider Namespace: Microsoft.Compute
API Version: 2019-12-01
Resource Types (Resource Group Scope):
- availabilitySets
- galleries
- galleries/applications
- galleries/applications/versions
- galleries/images
- galleries/images/versions
- hostGroups
- hostGroups/hosts
- images
- proximityPlacementGroups
- sshPublicKeys
- virtualMachines
- virtualMachineScaleSets
- virtualMachineScaleSets/virtualmachines
- virtualMachineScaleSets/virtualMachines/extensions
================================================================================================================================
================================================================================================================================
Filename: /workspaces/azure-resource-manager-schemas/schemas/2020-05-01/Microsoft.Compute.json
Provider Namespace: Microsoft.Compute
API Version: 2020-05-01
Resource Types (Resource Group Scope):
- diskAccesses
- diskEncryptionSets
- disks
- snapshots
================================================================================================================================
================================================================================================================================
Filename: /workspaces/azure-resource-manager-schemas/schemas/2020-06-01/Microsoft.Compute.json
Provider Namespace: Microsoft.Compute
API Version: 2020-06-01
Resource Types (Resource Group Scope):
- availabilitySets
- hostGroups
- hostGroups/hosts
- images
- proximityPlacementGroups
- sshPublicKeys
- virtualMachines
- virtualMachineScaleSets
- virtualMachineScaleSets/virtualmachines
- virtualMachineScaleSets/virtualMachines/extensions
- virtualMachineScaleSets/virtualMachines/runCommands
- virtualMachines/runCommands
================================================================================================================================
================================================================================================================================
Filename: /workspaces/azure-resource-manager-schemas/schemas/2020-06-30/Microsoft.Compute.json
Provider Namespace: Microsoft.Compute
API Version: 2020-06-30
Resource Types (Resource Group Scope):
- diskAccesses
- diskEncryptionSets
- disks
- snapshots
================================================================================================================================
================================================================================================================================
Filename: /workspaces/azure-resource-manager-schemas/schemas/2020-09-30/Microsoft.Compute.json
Provider Namespace: Microsoft.Compute
API Version: 2020-09-30
Resource Types (Resource Group Scope):
- diskAccesses
- diskAccesses/privateEndpointConnections
- diskEncryptionSets
- disks
- galleries
- galleries/applications
- galleries/applications/versions
- galleries/images
- galleries/images/versions
- snapshots
================================================================================================================================
================================================================================================================================
Filename: /workspaces/azure-resource-manager-schemas/schemas/2020-10-01-preview/Microsoft.Compute.json
Provider Namespace: Microsoft.Compute
API Version: 2020-10-01-preview
Resource Types (Resource Group Scope):
- cloudServices
- cloudServices/updateDomains
================================================================================================================================
================================================================================================================================
Filename: /workspaces/azure-resource-manager-schemas/schemas/2020-12-01/Microsoft.Compute.json
Provider Namespace: Microsoft.Compute
API Version: 2020-12-01
Resource Types (Resource Group Scope):
- availabilitySets
- diskAccesses
- diskAccesses/privateEndpointConnections
- diskEncryptionSets
- disks
- hostGroups
- hostGroups/hosts
- images
- proximityPlacementGroups
- snapshots
- sshPublicKeys
- virtualMachines
- virtualMachineScaleSets
- virtualMachineScaleSets/virtualmachines
- virtualMachineScaleSets/virtualMachines/extensions
- virtualMachineScaleSets/virtualMachines/runCommands
- virtualMachines/runCommands
================================================================================================================================
================================================================================================================================
Filename: /workspaces/azure-resource-manager-schemas/schemas/2021-03-01/Microsoft.Compute.json
Provider Namespace: Microsoft.Compute
API Version: 2021-03-01
Resource Types (Resource Group Scope):
- availabilitySets
- cloudServices
- cloudServices/updateDomains
- hostGroups
- hostGroups/hosts
- images
- proximityPlacementGroups
- restorePointCollections
- restorePointCollections/restorePoints
- sshPublicKeys
- virtualMachines
- virtualMachineScaleSets
- virtualMachineScaleSets/virtualmachines
- virtualMachineScaleSets/virtualMachines/extensions
- virtualMachineScaleSets/virtualMachines/runCommands
- virtualMachines/runCommands
================================================================================================================================
================================================================================================================================
Filename: /workspaces/azure-resource-manager-schemas/schemas/2021-04-01/Microsoft.Compute.json
Provider Namespace: Microsoft.Compute
API Version: 2021-04-01
Resource Types (Resource Group Scope):
- availabilitySets
- capacityReservationGroups
- capacityReservationGroups/capacityReservations
- diskAccesses
- diskAccesses/privateEndpointConnections
- diskEncryptionSets
- disks
- hostGroups
- hostGroups/hosts
- images
- proximityPlacementGroups
- restorePointCollections
- restorePointCollections/restorePoints
- snapshots
- sshPublicKeys
- virtualMachines
- virtualMachineScaleSets
- virtualMachineScaleSets/virtualmachines
- virtualMachineScaleSets/virtualMachines/extensions
- virtualMachineScaleSets/virtualMachines/runCommands
- virtualMachines/runCommands
================================================================================================================================
================================================================================================================================
Filename: /workspaces/azure-resource-manager-schemas/schemas/2021-07-01/Microsoft.Compute.json
Provider Namespace: Microsoft.Compute
API Version: 2021-07-01
Resource Types (Resource Group Scope):
- availabilitySets
- capacityReservationGroups
- capacityReservationGroups/capacityReservations
- galleries
- galleries/applications
- galleries/applications/versions
- galleries/images
- galleries/images/versions
- hostGroups
- hostGroups/hosts
- images
- proximityPlacementGroups
- restorePointCollections
- restorePointCollections/restorePoints
- sshPublicKeys
- virtualMachines
- virtualMachineScaleSets
- virtualMachineScaleSets/virtualmachines
- virtualMachineScaleSets/virtualMachines/extensions
- virtualMachineScaleSets/virtualMachines/runCommands
- virtualMachines/runCommands
================================================================================================================================
```

### CODE REVIEW

**Comment by grizzlytheodore** [comment]
@anthony-c-martin  please review/merge!

**Comment by anthony-c-martin** [comment]
I ran the generation and pushed to this branch, but looks like there are quite a few test failures that'll need fixing up. Will try to get to this when I have a chance.

**Comment by grizzlytheodore** [comment]
@anthony-c-martin  thank you!

**Review by anthony-c-martin — APPROVED** [review]

**Comment by grizzlytheodore** [comment]
will this get auto merged? @anthony-c-martin

**Comment by anthony-c-martin** [comment]
> will this get auto merged? @anthony-c-martin

Still hitting some test failures, but I'll merge it as soon as I'm able to get this passing.

**Pull request merged**
