### PR TITLE
Onboarding Microsoft.IotCentral for autogeneration

### PR DESCRIPTION
**Pull request by anthony-c-martin**
```
> azure-schema-generator@1.0.0 generate-single C:\github\azure-resource-manager-schemas\generator
> ts-node cmd/generatesingle "iotcentral/resource-manager"

[C:\Users\antmarti\AppData\Local\Temp\schm_azspc] executing: git fsck
[C:\Users\antmarti\AppData\Local\Temp\schm_azspc] executing: git reset -q .
[C:\Users\antmarti\AppData\Local\Temp\schm_azspc] executing: git checkout -q -- .
[C:\Users\antmarti\AppData\Local\Temp\schm_azspc] executing: git clean -q -fd
[C:\Users\antmarti\AppData\Local\Temp\schm_azspc] executing: git gc
[C:\Users\antmarti\AppData\Local\Temp\schm_azspc] executing: git fetch
From https://github.com/azure/azure-rest-api-specs
 * [new branch]          dev-monitor-Microsoft.Insights-2018-03-01 -> origin/dev-monitor-Microsoft.Insights-2018-03-01
   fbc094f30..ef354ec8d  master                  -> origin/master
 * [new branch]          patch-1                 -> origin/patch-1
 * [new branch]          redis-preview-to-stable -> origin/redis-preview-to-stable
 + d66cb2199...2473e0345 sornaks/stablelicense   -> origin/sornaks/stablelicense  (forced update)
   10fa1f676..7e1b8208b  storage-dataplane-preview -> origin/storage-dataplane-preview
 * [new tag]             openapi-baselineTag-dev-monitor-Microsoft.Insights-2018-03-01 -> openapi-baselineTag-dev-monitor-Microsoft.Insights-2018-03-01
 * [new tag]             update-dev-monitor-Microsoft.Insights-2018-03-01__resource-manager_monitor_Microsoft.Insights_stable_2018-03-01 -> update-dev-monitor-Microsoft.Insights-2018-03-01__resource-manager_monitor_Microsoft.Insights_stable_2018-03-01
[C:\Users\antmarti\AppData\Local\Temp\schm_azspc] executing: git checkout -q origin/master
[C:\github\azure-resource-manager-schemas\generator] executing: autorest-beta.cmd --azureresourceschema --output-folder=C:\Users\antmarti\AppData\Local\Temp\y5n76xoohko --tag=all-api-versions --api-version=2018-09-01 --title=none C:\Users\antmarti\AppData\Local\Temp\schm_azspc\specification\iotcentral\resource-manager\readme.md
AutoRest code generation utility [version: 3.0.6122; node: v10.15.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\github\azure-resource-manager-schemas\generator\node_modules\@autorest\core\dist' (3.0.6139)
   Loading local AutoRest extension '@autorest/azureresourceschema' (C:\github\azure-resource-manager-schemas\generator\node_modules\@autorest\azureresourceschema)
[5.83 s] Generation Complete
================================================================================================================================
Filename: C:\github\azure-resource-manager-schemas\schemas\2018-09-01\Microsoft.IoTCentral.json
Provider Namespace: Microsoft.IoTCentral
API Version: 2018-09-01
Resource Types (Resource Group Scope):
- IoTApps
================================================================================================================================
```

### CODE REVIEW

**Comment by zzcodework** [comment]
Thank you Anthony, I have two questions:

1. Is it safe and suggested to remove our 2017-07-01-privatepreview version?
2. The test file is also deleted, so the auto generator will run its own tests?

**Comment by anthony-c-martin** [comment]
> Thank you Anthony, I have two questions:
> 
> 1. Is it safe and suggested to remove our 2017-07-01-privatepreview version?

Good point, let me look into why this is. I think we may just look at stable and preview versions. What's the reason you have a privatepreview API published - is this in use by non-private-preview customers?

> 2. The test file is also deleted, so the auto generator will run its own tests?

We rely on the tests that have been run as part of the swagger check-in. We continue to support the existing tests files, but don't require them for any further API versions added. The privatepreview test was removed to reflect the removed privatepreview API, but the `2018-09-01` test is still there.

**Comment by zzcodework** [comment]
Thanks for the reply, the privatepreview api was created long time back when we first started IoTCentral, I don't think we have customer using now, I asked the question because we still have the version in swagger, so want to make them aligned.
If removing obsoleted api is recommended for all the RPs, let's just remove it. :)

**Comment by poanchen** [comment]
I created a PR (https://github.com/anthony-c-martin/azure-resource-manager-schemas/pull/1) for adding the missing test for the new sku. @anthony-c-martin Please approve this PR in your forked repo so that that changes will come in along with the autogeneration

**Comment by poanchen** [comment]
Hey @ifeoluwaokunoren ,

Please review this PR and approve it thanks!

**Pull request merged**
