### PR TITLE
Enable apimanagement autogen

### PR DESCRIPTION
**Pull request by jorgecotillo**

### CODE REVIEW

**Comment by apclouds** [comment]
hi @leni-msft is autorest fixed?

**Comment by leni-msft** [comment]
hi @apclouds, it's not fixed yet. Autorest team is confirming the issue.

**Comment by apclouds** [comment]
@leni-msft any update here?

**Comment by leni-msft** [comment]
@apclouds It's already been enabled in https://github.com/Azure/azure-resource-manager-schemas/pull/1282/commits/3d07f9fcf166260853a15a61825b55406834f8a2 . So ok to close this PR.

**Pull request closed without merging**
