### PR TITLE
use multiapi instead of all-api-versions

### PR DESCRIPTION
**Pull request by leni-msft**
Replaces https://github.com/Azure/azure-resource-manager-schemas/pull/1148

### CODE REVIEW

**Comment by anthony-c-martin** [comment]
@leni-msft - just wanted to confirm with you. When you re-run this, it successfully creates all the expected JSON files? If so, happy to sign off!

**Comment by leni-msft** [comment]
@anthony-c-martin The four batch pipelines executed successfully, and from the logs([batch0](https://dev.azure.com/azure/azure-resource-manager-schemas/_build/results?buildId=13771&view=logs&j=ae501f3d-63ca-563e-a3d9-7c46870865a7&t=5b372c7a-4bf1-530e-6011-652a8f555b0d), [batch1](https://dev.azure.com/azure/azure-resource-manager-schemas/_build/results?buildId=13786&view=logs&j=ae501f3d-63ca-563e-a3d9-7c46870865a7&t=5b372c7a-4bf1-530e-6011-652a8f555b0d), [batch2](https://dev.azure.com/azure/azure-resource-manager-schemas/_build/results?buildId=13789&view=logs&j=ae501f3d-63ca-563e-a3d9-7c46870865a7&t=5b372c7a-4bf1-530e-6011-652a8f555b0d), [batch3](https://dev.azure.com/azure/azure-resource-manager-schemas/_build/results?buildId=13792&view=logs&j=ae501f3d-63ca-563e-a3d9-7c46870865a7&t=5b372c7a-4bf1-530e-6011-652a8f555b0d)) we can see all the generated resources. So yes, I believe all expected JSON files have been created.

**Comment by anthony-c-martin** [comment]
> @anthony-c-martin The four batch pipelines executed successfully, and from the logs([batch0](https://dev.azure.com/azure/azure-resource-manager-schemas/_build/results?buildId=13771&view=logs&j=ae501f3d-63ca-563e-a3d9-7c46870865a7&t=5b372c7a-4bf1-530e-6011-652a8f555b0d), [batch1](https://dev.azure.com/azure/azure-resource-manager-schemas/_build/results?buildId=13786&view=logs&j=ae501f3d-63ca-563e-a3d9-7c46870865a7&t=5b372c7a-4bf1-530e-6011-652a8f555b0d), [batch2](https://dev.azure.com/azure/azure-resource-manager-schemas/_build/results?buildId=13789&view=logs&j=ae501f3d-63ca-563e-a3d9-7c46870865a7&t=5b372c7a-4bf1-530e-6011-652a8f555b0d), [batch3](https://dev.azure.com/azure/azure-resource-manager-schemas/_build/results?buildId=13792&view=logs&j=ae501f3d-63ca-563e-a3d9-7c46870865a7&t=5b372c7a-4bf1-530e-6011-652a8f555b0d)) we can see all the generated resources. So yes, I believe all expected JSON files have been created.

Awesome, thanks for confirming. The speedup you were able to achieve with this is amazing by the way!

**Review by anthony-c-martin — APPROVED** [review]

**Comment by leni-msft** [comment]
@anthony-c-martin Thanks for approving the PR! Could any of you help compete the PR? @apclouds @jorgecotillo It seems I have no permission to do so.

**Pull request merged**
