### PR TITLE
Added Missing refs to applicationGateways

### PR DESCRIPTION
**Pull request by QuasarSE**
Broken in PR #417 -- no references to Microsoft.Network/applicationGateways resource type.  Breaks schema validation of this type in VS Code, etc.

Added ref for all versions which have this type in the network schema: 2017-06-01, 2017-08-01, 2017-09-01, 2017-10-01, 2017-11-01, 2018-01-01.

Attn: @EvgenyAgafonchikov

### CODE REVIEW

**Comment by QuasarSE** [comment]
Should have said "broken" or "missed" in PR 417.  Either way, the type didn't get included with a number of Network additions in that PR.

**Comment by Tiano2017** [comment]
do we need to fix 2014-04-01-preview/deploymentTemplate.json as well?

**Comment by Tiano2017** [comment]
@EvgenyAgafonchikov  please take a look at this.

**Comment by EvgenyAgafonchikov** [comment]
@Tiano2017, I've got answer from my management that solution on this update should be taken by Application Gateways team.

@akshaysngupta, could you please have a look?

FYI: @MikhailTryakhov, @DeepakRajendranMsft

**Comment by Tiano2017** [comment]
@QuasarSE could you help update 2014-04-01-preview/deploymentTemplate.json as well?

**Comment by Tadimsky** [comment]
Can we get this in? It's frustrating not having AG in the ARM schema.

**Comment by Tiano2017** [comment]
created a separate PR #461 and merged that one.

**Pull request closed without merging**
