### PR TITLE
Adding schema to Microsoft.Cdn

### PR DESCRIPTION
**Pull request by kuangweizhang**
There are two api versions 2015-06-01 and 2016-04-02 included

### CODE REVIEW

**Comment by daschult** [comment]
I have auto-generated this schema in pull request https://github.com/Azure/azure-resource-manager-schemas/pull/151. Can you please take a look at the schema in that pull request and provide feedback on it?

**Comment by kuangweizhang** [comment]
@daschult That's amazing! This saves us lots of time. Kudos!

**Comment by wenwu449** [comment]
Please let me know if you prefer this PR or https://github.com/Azure/azure-resource-manager-schemas/pull/156 and close one of them.
Thanks.

**Comment by kuangweizhang** [comment]
Close since addressed in another PR

**Pull request closed without merging**
