### PR TITLE
Move "extensionsChild" definition to "definitions".

### PR DESCRIPTION
**Pull request by TianoMS**

### CODE REVIEW

**Comment by TianoMS** [comment]
@jluk can you please review this PR?

**Comment by jluk** [comment]
@TianoMS I'm not familiar with the implications of changing the resource name, someone in CRP would need to verify this

**Comment by TianoMS** [comment]
@waynekuo to review also. 

The change is to move the "extensionChild" definition to "definitions". There should be no change in any functions.

**Comment by waynekuo** [comment]
Looks good to me. I assume there's no functional impact and current unit tests are passing?

**Comment by TianoMS** [comment]
Right. Now functional impact. Test passed.

**Pull request merged**
