### PR TITLE
Adding LogicApps resource schema for API 2016-06-01

### PR DESCRIPTION
**Pull request by pscofield**

### CODE REVIEW

**Comment by chaliy** [comment]
Hey @TianoMS , I am getting error when use integrationAccount from this version.

`[resourceId('Microsoft.Logic/integrationAccounts', 'valid-name-of-integration-account')]`

And error is:

> The request content is not valid and could not be deserialized: 'Error converting value \"/subscriptions/e0845a75-1e77-4ff1-ae74-724d9ca9b827/resourceGroups/valid-group-name/providers/Microsoft.Logic/integrationAccounts/valid-name-of-integration-account\" to type 'Microsoft.Azure.Flow.Data.Definitions.IntegrationAccountReference'. Path 'properties.integrationAccount', line 1, position 415.'

**Comment by pscofield** [comment]
@chaliy, is it the backslash at the end of the string? If not, can you share the file and the repro? Thanks!

**Comment by chaliy** [comment]
@pscofield backslash is encoding.

azuredeploy.json

```
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {},
  "variables": {
    "service_plan_name": "file-etl-farm",
    "service_plan_id": "[resourceId('Microsoft.Web/serverfarms', variables('service_plan_name'))]",
    "workflow_name": "file-etl",
    "integration_account_name": "integration",
    "integration_account_id": "[resourceId('Microsoft.Logic/integrationAccounts', variables('integration_account_name'))]",
    "storage_api_version": "[providers('Microsoft.Storage', 'storageAccounts').apiVersions[0]]"
  },
  "resources": [
    {
      "type": "Microsoft.Web/serverfarms",
      "name": "[variables('service_plan_name')]",
      "sku": {
        "name": "S1",
        "tier": "Standard",
        "size": "S1",
        "family": "S",
        "capacity": 1
      },
      "properties": {
        "name": "[variables('service_plan_name')]",
        "numberOfWorkers": 1
      },
      "apiVersion": "2015-08-01",
      "location": "[resourceGroup().location]",
      "dependsOn": []
    },
    {
      "type": "Microsoft.Logic/integrationAccounts",
      "sku": {
        "name": "Free"
      },
      "name": "[variables('integration_account_name')]",
      "properties": {},
      "apiVersion": "2015-08-01-preview",
      "location": "[resourceGroup().location]"
    },
    {
      "type": "Microsoft.Logic/workflows",
      "name": "[variables('workflow_name')]",
      "properties": {
        "state": "Enabled",
        "sku": {
          "name": "Standard",
          "plan": {
            "id": "[variables('service_plan_id')]"
          }
        },
        "integrationAccount": "[variables('integration_account_id')]",
        "definition": {
          "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-04-01-preview/workflowdefinition.json#",
          "contentVersion": "1.0.0.0",
          "parameters": {},
          "triggers": {
            "recurrence": {
              "type": "recurrence",
              "recurrence": {
                "frequency": "Hour",
                "interval": 1
              }
            }
          },
          "actions": {
            "Http": {
              "runAfter": {},
              "type": "Http",
              "inputs": {
                "method": "GET",
                "uri": "https://raw.githubusercontent.com/psget/psget/master/Directory.xml"
              }
            }
          },
          "outputs": {}
        },
        "parameters": {}
      },
      "apiVersion": "2016-06-01",
      "location": "[resourceGroup().location]",
      "dependsOn": [
        "[variables('service_plan_id')]",
        "[variables('integration_account_id')]"
      ]
    }
  ]
}
```

Command to execute:
 ❯ azure group deployment create -q -m complete -f azuredeploy.json reproduce-integration-accout-issue default

**Comment by rarayudu** [comment]
@chaliy,

The way you are providing the IntegrationAccount details is in correct.

Please provide the integration account details in the following way.

"integrationAccount": {
    "id": "[variables('integration_account_id')]"
},

instead of - "integrationAccount": "[variables('integration_account_id')]", in your ARM template.

Let us know if you face any other issues.

Thanks.

**Comment by chaliy** [comment]
@rarayudu that works! Thank you!

Just curious. May be you know. Is it planned that schemas and mappings in integration account will be also managed by resource manager(e.g. will be usable in resource templates)?

**Comment by rarayudu** [comment]
@chaliy,

Even today they can be managed by Azure Resource Mange (ARM). You can do something like this to create the schema/maps through ARM resource template.

`{
      "type": "Microsoft.Logic/integrationAccounts",
      "sku": {
        "name": "Free"
      },
      "name": "[variables('integration_account_name')]",
      "properties": { },
      "apiVersion": "2015-08-01-preview",
      "location": "[resourceGroup().location]"
    },
    {
      "type": "Microsoft.Logic/integrationAccounts/schemas",
      "name": "[concat(variables('integration_account_name'), '/', variables('schema_name'))]",
      "properties": {
        "schemaType": "xml",
        "content": "<?xml version=\"1.0\" encoding=\"utf-8\" ?><xs:schema xmlns:xs=\"http://www.w3.org/2001/XMLSchema\"><xs:element name='Root'><xs:complexType><xs:sequence><xs:element name='CompanyName' type='xs:string'/><xs:element name='ContactName' type='xs:string'/></xs:sequence><xs:attribute name='CustomerID' type='xs:token'/></xs:complexType></xs:element></xs:schema>",
        "contentType": "application/xml"
      },
      "apiVersion": "2015-08-01-preview",
      "location": "[resourceGroup().location]",
      "dependsOn": [
        "[variables('integration_account_id')]"
      ]
    },
    {
      "type": "Microsoft.Logic/integrationAccounts/maps",
      "name": "[concat(variables('integration_account_name'), '/', variables('map_name'))]",
      "properties": {
        "mapType": "xslt",
        "content": "<?xml version=\"1.0\" encoding=\"utf-8\"?><xsl:stylesheet version=\"1.0\" xmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\" xmlns:msxsl=\"urn:schemas-microsoft-com:xslt\" exclude-result-prefixes=\"msxsl\"><xsl:output method=\"xml\" indent=\"yes\"/><xsl:template match=\"@* | node()\"><xsl:copy><xsl:apply-templates select=\"@* | node()\"/></xsl:copy></xsl:template></xsl:stylesheet>",
        "contentType": "application/xml"
      },
      "apiVersion": "2015-08-01-preview",
      "location": "[resourceGroup().location]",
      "dependsOn": [
        "[variables('integration_account_id')]"
      ]
    },`

Let us know of you need any more details.

**Comment by chaliy** [comment]
@rarayudu oh! Thank you! This is awesome.

Sorry but one more question. How did you know that such resources types and their schema exist? Is there anything public that I can look? I cannot find anything about it in this repo. I am still looking for a way to define bloc container in storageAccount, and will probably need other resources as well.

**Comment by rarayudu** [comment]
@chaliy 

I am a dev in Azure logic apps team. Integration Accounts (Enterprise integration features in the logic apps) is a new offering for the Integration scenarios. We will work on adding more documentation around these scenarios.

If you have any questions about logic apps, you can post on MSDN or send an email to "logicappsbug@microsoft.com".

for this - "I am still looking for a way to define bloc container in storageAccount, and will probably need other resources as well." - Can you please explain a bit more about your scenario?

Thanks, Rama.

**Pull request merged**
