### PR TITLE
Add Microsoft.Genomics.json to schemas

### PR DESCRIPTION
**Pull request by jbagga**
Add Microsoft.Genomics.json to schemas

The two tests specified in README passed.

### CODE REVIEW

**Comment by Tiano2017** [comment]
This was published today. Let me know if you still see the issue.

**Comment by jbagga** [comment]
The template looks updated. But when trying to generate an automation script, I still see the error
```
The schema of resource type 'Microsoft.Genomics/accounts' is not available. Resources of this type will not be exported to the template. (Code: ResourceTypeSchemaNotFound, Target: Microsoft.Genomics/accounts)
```
I added the schema as part of this PR in a new folder (the version folder didn't exist before). Can you let me know what else I need to do to make this work?

**Comment by Tiano2017** [comment]
for export template, the change has not been deployed to all regions yet. will finish the rest of regions by Tuesday.

**Comment by jbagga** [comment]
Thanks a lot! Appreciate the help :)

**Comment by jbagga** [comment]
@Tiano2017 The template is generated without errors
```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "accounts_jassWestUS_name": {
            "defaultValue": "jassWestUS",
            "type": "String"
        }
    },
    "variables": {},
    "resources": [
        {
            "comments": "Generalized from resource: '/subscriptions/4f6acf54-d28d-4d5b-9560-1bf1f526f943/resourceGroups/jassTest/providers/Microsoft.Genomics/accounts/jassWestUS'.",
            "type": "Microsoft.Genomics/accounts",
            "name": "[parameters('accounts_jassWestUS_name')]",
            "apiVersion": "2017-08-01-preview",
            "location": "westus",
            "scale": null,
            "properties": {
                "maxConcurrentWorkflowsQuota": 20,
                "endpoint": "https://westus.microsoftgenomics.net",
                "provisioningState": "Succeeded"
            },
            "dependsOn": []
        }
    ]
}
```
But I am unable to use it to deploy because the provisioningState is a readOnly property. What do I need to do to allow provisioning the resource? Also I did not define "properties" in our schema but they show up in the Automation Script. Any suggestions/ideas/docs?

**Pull request merged**
