### PR TITLE
Update autorest core version

### PR DESCRIPTION
**Pull request by leni-msft**
To unblock onboarding MixedReality and some ApiManagement schemas, due to autorest issues: Azure/perks/issues/83 and Azure/autorest/issues/3616

### CODE REVIEW

**Review by anthony-c-martin — APPROVED** [review]
Looks good!

**Comment by leni-msft** [comment]
There seems a regression bug. Raised an issue Azure/autorest/issues/3747

**Comment by leni-msft** [comment]
hi @anthony-c-martin , the autorest regression bug is resolved. Please help check again. Note the https://github.com/Azure/azure-resource-manager-schemas/pull/1427/commits/d504431c987c1ca02b1a42facf558a72a6181de1 to fix the test cases.

**Comment by anthony-c-martin** [comment]
:shipit:

**Pull request merged**
