### PR TITLE
Update accepted KeyVault permissions to include "all"

### PR DESCRIPTION
**Pull request by pshelton-skype**
Deployment with the following template succeeds and results in a Key Vault with all permissions applied successfully.

**keyvault.template.json:**
```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": { },
    "variables": {
        "allKeyVaultPermissions": {
            "keys": [
                "All"
            ],
            "secrets": [
                "All"
            ],
            "certificates": [
                "All"
            ],
            "storage": [
                "All"
            ]
        }
    },
    "resources": [
        {
            "type": "Microsoft.KeyVault/vaults",
            "name": "KeyVaultPermissionsTest",
            "apiVersion": "2015-06-01",
            "location": "Central US",
            "scale": null,
            "properties": {
                "sku": {
                    "family": "A",
                    "name": "Standard"
                },
                "tenantId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
                "accessPolicies": [
                    {
                        "tenantId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
                        "objectId": "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
                        "permissions": "[variables('allKeyVaultPermissions')]"
                    }
                ]
            },
            "dependsOn": []
        }
    ]
}
```
```
> New-AzureRmResourceGroupDeployment -ResourceGroupName KeyVaultPermissionsTest -TemplateFile .\keyvault.template.json

DeploymentName          : keyvault.template
ResourceGroupName       : KeyVaultPermissionsTest
ProvisioningState       : Succeeded
Timestamp               : 1/23/2018 7:59:03 PM
Mode                    : Incremental
...

> Get-AzureRMKeyVault -Name KeyVaultPermissionsTest

Vault Name                       : KeyVaultPermissionsTest
Resource Group Name              : KeyVaultPermissionsTest
Location                         : Central US
Resource ID                      : /subscriptions/cccccccc-cccc-cccc-cccc-cccccccccccc/resourceGroups/KeyVaultPermissio
                                   nsTest/providers/Microsoft.KeyVault/vaults/KeyVaultPermissionsTest
Vault URI                        : https://keyvaultpermissionstest.vault.azure.net/
Tenant ID                        : aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
SKU                              : Standard
Enabled For Deployment?          : False
Enabled For Template Deployment? :
Enabled For Disk Encryption?     :
Soft Delete Enabled?             :
Access Policies                  :
                                   Tenant ID                                  : aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
                                   Object ID                                  : bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb
                                   Application ID                             :
                                   Display Name                               : Parker Shelton (email@contoso.com)
                                   Permissions to Keys                        : All
                                   Permissions to Secrets                     : All
                                   Permissions to Certificates                : All
                                   Permissions to (Key Vault Managed) Storage : All
```
https://docs.microsoft.com/en-us/azure/templates/microsoft.keyvault/vaults#Permissions should be updated to reflect this.

### CODE REVIEW

**Comment by Tiano2017** [comment]
@pshelton-skype is this generated from swagger?

**Comment by pshelton-skype** [comment]
@Tiano2017 - Nope. How would one go about doing that? There's no Contributing.md and the Readme.md doesn't mention anything about swagger.

**Comment by Tiano2017** [comment]
@schaabs can you take a look at this change? My suggestion is fix the swagger file if this is an issue there as well.

**Comment by schaabs** [comment]
@Tiano2017 we explicitly removed the "all" permission from our latest swagger because this value is misleading.  The value "all" is still supported for compatibility reasons, but it doesn't actually result in all permissions being granted.  Specifically the "purge" permission is not added when "all" is specified.

**Comment by Tiano2017** [comment]
@pshelton-skype See Scott's reply above. I think he means we don't need to add "all" back.

**Comment by pshelton-skype** [comment]
I explicitly checked the existence of "purge" since it is a new permission, but I see it added by default for new ARM deployments of KV resources with "all" specified:

image

Is it at risk of breaking in new versions of the KV schema or of ARM, or did someone fix the bug where "purge" wasn't properly added?

**Comment by schaabs** [comment]
@pshelton-skype I believe this is a UX bug.  In the case of the above template AccessPolicy is actually stored as having the permission "all" and this is supported by legacy operations, but calls to new operations such as keyPurge would fail as it expects the explicit permission 'purge' to be included.  I believe that the portal is incorrectly deciphering 'all' as including the purge permission, but this is not the case.

**Comment by pshelton-skype** [comment]
Hmm, interesting. You are correct. "Purge" is disallowed even though the Azure Portal and PowerShell are reporting "All" permissions. I'll bump this over to those teams to argue that they properly expand "All" when used in a template or PowerShell command to the correct list of allowed permissions.

```
> Remove-AzureKeyVaultSecret -VaultName KeyVaultPermissionsTest -Name TestSecret -InRemovedState

Confirm
Are you sure you want to perform this action?
Performing the operation "Purge secret" on target "TestSecret".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): Y

Confirm
Are you sure you want to purge secret 'TestSecret'.
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): Y
Remove-AzureKeyVaultSecret : Operation "purge" is not allowed by vault policy
At line:1 char:1
+ Remove-AzureKeyVaultSecret -VaultName KeyVaultPermissionsTest -Name TestSecr ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Remove-AzureKeyVaultSecret], KeyVaultErrorException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.RemoveAzureKeyVaultSecret
```

**Pull request closed without merging**
