### PR TITLE
Fix Microsoft.Security autogeneration

### PR DESCRIPTION
**Pull request by larsmaes-sogeti**
The autogeneartion of Microsoft.Security failed because of some missing resource configurations.

This PR adds the missing configurations thus fixing the autogeneration

### CODE REVIEW

**Comment by larsmaes-sogeti** [comment]
#2959

**Comment by anthony-c-martin** [comment]
Thank you for fixing this!

**Comment by larsmaes-sogeti** [comment]
@anthony-c-martin had to fix some formatting issues, can you approve the workflow run again?

**Comment by larsmaes-sogeti** [comment]
Looks good now @anthony-c-martin can you review? Reason is that I'm creating policies that configure defender plans :)

**Review by anthony-c-martin — APPROVED** [review]

**Comment by anthony-c-martin** [comment]
Oops, done!

**Pull request merged**
