### PR TITLE
Onboarding Microsoft.Migrate for autogeneration

### PR DESCRIPTION
**Pull request by innosam**
AutoRest code generation utility [cli version: 3.0.6247; node: v10.16.3,
max-memory: 1280 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core
   'C:\Users\hsingh\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist'
   (3.0.6320)
   (node:9020) ExperimentalWarning: The fs.promises API is experimental
      Installing AutoRest extension '@autorest/azureresourceschema'
      (3.0.92)
         Installed AutoRest extension '@autorest/azureresourceschema'
	 (3.0.92->3.0.92)
	 Processing batch task -
	 {"tag":"schema-migrate-2019-10-01-preview"} .
	 [21.17 s] Generation Complete
	 ================================================================================================================================
	 Filename:
	 c:\code\azure-resource-manager-schemas\schemas\2019-10-01-preview\Microsoft.Migrate.json
	 Provider Namespace: Microsoft.Migrate
	 API Version: 2019-10-01-preview
	 Resource Types (Resource Group Scope):
	 - moveCollections
	 - moveCollections/moveResources
	 ================================================================================================================================

### CODE REVIEW

**Comment by innosam** [comment]
AutoRest code generation utility [cli version: 3.0.6247; node: v10.16.3,
max-memory: 1280 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Loading AutoRest core
'C:\Users\hsingh.autorest@autorest_core@3.0.6320\node_modules@autorest\core\dist'
(3.0.6320)
(node:9020) ExperimentalWarning: The fs.promises API is experimental
Installing AutoRest extension '@autorest/azureresourceschema'
(3.0.92)
Installed AutoRest extension '@autorest/azureresourceschema'
(3.0.92->3.0.92)
Processing batch task -
{"tag":"schema-migrate-2019-10-01-preview"} .
[21.17 s] Generation Complete
================================================================================================================================
Filename:
c:\code\azure-resource-manager-schemas\schemas\2019-10-01-preview\Microsoft.Migrate.json
Provider Namespace: Microsoft.Migrate
API Version: 2019-10-01-preview
Resource Types (Resource Group Scope):
- moveCollections
- moveCollections/moveResources
================================================================================================================================

**Review by jorgecotillo — APPROVED** [review]
LGTM, @anthony-c-martin can you also double check this PR?

**Comment by jorgecotillo** [comment]
Let's wait for Anthony for a final review then we can merge this PR if all is good.

**Review by anthony-c-martin — APPROVED** [review]
Looks good!

**Pull request merged**
