### PR TITLE
Automation schema

### PR DESCRIPTION
**Pull request by neilpeterson**
```
Neils-MacBook-Pro-2:generator neilpeterson$ npm run generate-single automation/resource-manager

> azure-schema-generator@1.0.0 generate-single /Users/neilpeterson/Documents/code/azure-resource-manager-schemas/generator
> ts-node cmd/generatesingle "automation/resource-manager"

[/var/folders/dk/z8jv71654dg3myb28zk484_40000gn/T/schm_azspc] executing: git fsck
[/var/folders/dk/z8jv71654dg3myb28zk484_40000gn/T/schm_azspc] executing: git clone https://github.com/azure/azure-rest-api-specs /var/folders/dk/z8jv71654dg3myb28zk484_40000gn/T/schm_azspc
Cloning into '/var/folders/dk/z8jv71654dg3myb28zk484_40000gn/T/schm_azspc'...
Checking out files: 100% (27644/27644), done.
[/var/folders/dk/z8jv71654dg3myb28zk484_40000gn/T/schm_azspc] executing: git reset -q .
[/var/folders/dk/z8jv71654dg3myb28zk484_40000gn/T/schm_azspc] executing: git checkout -q -- .
[/var/folders/dk/z8jv71654dg3myb28zk484_40000gn/T/schm_azspc] executing: git clean -q -fd
[/var/folders/dk/z8jv71654dg3myb28zk484_40000gn/T/schm_azspc] executing: git gc
[/var/folders/dk/z8jv71654dg3myb28zk484_40000gn/T/schm_azspc] executing: git fetch -q
[/var/folders/dk/z8jv71654dg3myb28zk484_40000gn/T/schm_azspc] executing: git checkout -q origin/master
[/Users/neilpeterson/Documents/code/azure-resource-manager-schemas/generator] executing: autorest-beta --version=3.0.6179 --use=@autorest/azureresourceschema@3.0.73 --azureresourceschema --output-folder=/var/folders/dk/z8jv71654dg3myb28zk484_40000gn/T/p7yrm2om67 --tag=all-api-versions --api-version=2017-05-15-preview --title=none /var/folders/dk/z8jv71654dg3myb28zk484_40000gn/T/schm_azspc/specification/automation/resource-manager/readme.md

WARNING: AutoRest has not been tested with Node versions greater than v10.

AutoRest code generation utility [version: 3.0.6149; node: v13.7.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      '/Users/neilpeterson/.autorest/@autorest_core@3.0.6179/node_modules/@autorest/core/dist' (3.0.6179)
   Loading AutoRest extension '@autorest/azureresourceschema' (3.0.73->3.0.73)
[43.57 s] Generation Complete
================================================================================================================================
Filename: /Users/neilpeterson/Documents/code/azure-resource-manager-schemas/schemas/2017-05-15-preview/Microsoft.Automation.json
Provider Namespace: Microsoft.Automation
API Version: 2017-05-15-preview
Resource Types (Resource Group Scope):
- automationAccounts/jobs
- automationAccounts/softwareUpdateConfigurations
- automationAccounts/sourceControls
- automationAccounts/sourceControls/sourceControlSyncJobs
================================================================================================================================
[/Users/neilpeterson/Documents/code/azure-resource-manager-schemas/generator] executing: autorest-beta --version=3.0.6179 --use=@autorest/azureresourceschema@3.0.73 --azureresourceschema --output-folder=/var/folders/dk/z8jv71654dg3myb28zk484_40000gn/T/6s3iauo7eko --tag=all-api-versions --api-version=2015-10-31 --title=none /var/folders/dk/z8jv71654dg3myb28zk484_40000gn/T/schm_azspc/specification/automation/resource-manager/readme.md

WARNING: AutoRest has not been tested with Node versions greater than v10.

AutoRest code generation utility [version: 3.0.6149; node: v13.7.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      '/Users/neilpeterson/.autorest/@autorest_core@3.0.6179/node_modules/@autorest/core/dist' (3.0.6179)
   Loading AutoRest extension '@autorest/azureresourceschema' (3.0.73->3.0.73)
[66.4 s] Generation Complete
================================================================================================================================
Filename: /Users/neilpeterson/Documents/code/azure-resource-manager-schemas/schemas/2015-10-31/Microsoft.Automation.json
Provider Namespace: Microsoft.Automation
API Version: 2015-10-31
Resource Types (Resource Group Scope):
- automationAccounts
- automationAccounts/certificates
- automationAccounts/compilationjobs
- automationAccounts/configurations
- automationAccounts/connections
- automationAccounts/connectionTypes
- automationAccounts/credentials
- automationAccounts/jobs
- automationAccounts/jobSchedules
- automationAccounts/modules
- automationAccounts/nodeConfigurations
- automationAccounts/runbooks
- automationAccounts/runbooks/draft
- automationAccounts/schedules
- automationAccounts/variables
- automationAccounts/watchers
- automationAccounts/webhooks
================================================================================================================================
[/Users/neilpeterson/Documents/code/azure-resource-manager-schemas/generator] executing: autorest-beta --version=3.0.6179 --use=@autorest/azureresourceschema@3.0.73 --azureresourceschema --output-folder=/var/folders/dk/z8jv71654dg3myb28zk484_40000gn/T/1kxuqkaay8b --tag=all-api-versions --api-version=2018-01-15 --title=none /var/folders/dk/z8jv71654dg3myb28zk484_40000gn/T/schm_azspc/specification/automation/resource-manager/readme.md

WARNING: AutoRest has not been tested with Node versions greater than v10.

AutoRest code generation utility [version: 3.0.6149; node: v13.7.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      '/Users/neilpeterson/.autorest/@autorest_core@3.0.6179/node_modules/@autorest/core/dist' (3.0.6179)
   Loading AutoRest extension '@autorest/azureresourceschema' (3.0.73->3.0.73)
[33.57 s] Generation Complete
================================================================================================================================
Filename: /Users/neilpeterson/Documents/code/azure-resource-manager-schemas/schemas/2018-01-15/Microsoft.Automation.json
Provider Namespace: Microsoft.Automation
API Version: 2018-01-15
Resource Types (Resource Group Scope):
- automationAccounts/compilationjobs
- automationAccounts/nodeConfigurations
================================================================================================================================
[/Users/neilpeterson/Documents/code/azure-resource-manager-schemas/generator] executing: autorest-beta --version=3.0.6179 --use=@autorest/azureresourceschema@3.0.73 --azureresourceschema --output-folder=/var/folders/dk/z8jv71654dg3myb28zk484_40000gn/T/47kl6qvf694 --tag=all-api-versions --api-version=2018-06-30 --title=none /var/folders/dk/z8jv71654dg3myb28zk484_40000gn/T/schm_azspc/specification/automation/resource-manager/readme.md

WARNING: AutoRest has not been tested with Node versions greater than v10.

AutoRest code generation utility [version: 3.0.6149; node: v13.7.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      '/Users/neilpeterson/.autorest/@autorest_core@3.0.6179/node_modules/@autorest/core/dist' (3.0.6179)
   Loading AutoRest extension '@autorest/azureresourceschema' (3.0.73->3.0.73)
[31.61 s] Generation Complete
================================================================================================================================
Filename: /Users/neilpeterson/Documents/code/azure-resource-manager-schemas/schemas/2018-06-30/Microsoft.Automation.json
Provider Namespace: Microsoft.Automation
API Version: 2018-06-30
Resource Types (Resource Group Scope):
- automationAccounts/python2Packages
- automationAccounts/runbooks
- automationAccounts/runbooks/draft
================================================================================================================================
```

### CODE REVIEW

**Comment by neilpeterson** [comment]
@anthony-c-martin , @ifeoluwaokunoren 

I am testing out this process with `automation/resource-manager`. The generation process seems to have run ok however I am hitting an issue with one test. From what I can tell, the error is related to [the SourceControlSecurityTokenProperties property / object](https://docs.microsoft.com/en-us/azure/templates/microsoft.automation/2017-05-15-preview/automationaccounts/sourcecontrols#sourcecontrolsecuritytokenproperties-object), however the schema looks ok to me.

```
AssertionError: 
Actual: [
  {
    "message": "Data does not match any schemas from \"oneOf\"",
    "dataPath": "/properties",
    "schemaPath": "/properties/properties/oneOf",
    "subErrors": [
      {
        "message": "Data does not match any schemas from \"oneOf\"",
        "dataPath": "/properties/securityToken",
        "schemaPath": "/properties/properties/oneOf/0/properties/securityToken/oneOf",
        "subErrors": [
          {
            "message": "Invalid type: string (expected object)",
            "dataPath": "/properties/securityToken",
            "schemaPath": "/properties/properties/oneOf/0/properties/securityToken/oneOf/0/type",
            "subErrors": []
          },
          {
            "message": "String does not match pattern: ^\\[([^\\[].*)?\\]$",
            "dataPath": "/properties/securityToken",
            "schemaPath": "/properties/properties/oneOf/0/properties/securityToken/oneOf/1/pattern",
            "subErrors": []
          }
        ]
      },
      {
        "message": "Invalid type: object (expected string)",
        "dataPath": "/properties",
        "schemaPath": "/properties/properties/oneOf/1/type",
        "subErrors": []
      }
    ]
  }
]
Expected: []
Expected result not to contain errors, but found errors.: expected [ Array(1) ] to deeply equal []
    at assertErrors (schemaTestsRunner.ts:112:16)
    at Object.execute (schemaTestsRunner.ts:201:5)
    at Context.<anonymous> (tests.ts:190:11)
```

Any thoughts on this?

Thanks

**Comment by anthony-c-martin** [comment]
> @anthony-c-martin , @ifeoluwaokunoren
> 
> I am testing out this process with `automation/resource-manager`. The generation process seems to have run ok however I am hitting an issue with one test. From what I can tell, the error is related to [the SourceControlSecurityTokenProperties property / object](https://docs.microsoft.com/en-us/azure/templates/microsoft.automation/2017-05-15-preview/automationaccounts/sourcecontrols#sourcecontrolsecuritytokenproperties-object), however the schema looks ok to me.
> 
> ```
> AssertionError: 
> Actual: [
>   {
>     "message": "Data does not match any schemas from \"oneOf\"",
>     "dataPath": "/properties",
>     "schemaPath": "/properties/properties/oneOf",
>     "subErrors": [
>       {
>         "message": "Data does not match any schemas from \"oneOf\"",
>         "dataPath": "/properties/securityToken",
>         "schemaPath": "/properties/properties/oneOf/0/properties/securityToken/oneOf",
>         "subErrors": [
>           {
>             "message": "Invalid type: string (expected object)",
>             "dataPath": "/properties/securityToken",
>             "schemaPath": "/properties/properties/oneOf/0/properties/securityToken/oneOf/0/type",
>             "subErrors": []
>           },
>           {
>             "message": "String does not match pattern: ^\\[([^\\[].*)?\\]$",
>             "dataPath": "/properties/securityToken",
>             "schemaPath": "/properties/properties/oneOf/0/properties/securityToken/oneOf/1/pattern",
>             "subErrors": []
>           }
>         ]
>       },
>       {
>         "message": "Invalid type: object (expected string)",
>         "dataPath": "/properties",
>         "schemaPath": "/properties/properties/oneOf/1/type",
>         "subErrors": []
>       }
>     ]
>   }
> ]
> Expected: []
> Expected result not to contain errors, but found errors.: expected [ Array(1) ] to deeply equal []
>     at assertErrors (schemaTestsRunner.ts:112:16)
>     at Object.execute (schemaTestsRunner.ts:201:5)
>     at Context.<anonymous> (tests.ts:190:11)
> ```
> 
> Any thoughts on this?
> 
> Thanks

Looks like the [test data](https://github.com/Azure/azure-resource-manager-schemas/blob/master/tests/2017-05-15-preview/Microsoft.Automation.tests.json#L61) is structured incorrectly - securityToken is defined as a string whereas the schema is expecting an object.

According to [docs](https://docs.microsoft.com/en-us/azure/templates/microsoft.automation/2017-05-15-preview/automationaccounts/sourcecontrols#template-format) and the newly-generated schema, this should actually be an object. 

I think this test could be fixed by replacing the test data with:
```
"securityToken": {
  "accessToken": "3a326f7a0dcd343ea58fee21f2fd5fb4c1234567",
  "tokenType": "PersonalAccessToken"
},
```

**Comment by neilpeterson** [comment]
@anthony-c-martin yep, this makes sense, thanks.

**Comment by anthony-c-martin** [comment]
LGTM. I think @ifeoluwaokunoren is going to ask the RP team to also review this.

**Pull request merged**
