### PR TITLE
Added Microsoft.VMware resource schema

### PR DESCRIPTION
**Pull request by parveenchahal**
Command output:
```
D:\azure-resource-manager-schemas\generator>npm run generate-single arcvmware/resource-manager

> azure-schema-generator@1.0.0 generate-single D:\azure-resource-manager-schemas\generator
> ts-node cmd/generatesingle "arcvmware/resource-manager"

[D:\azure-resource-manager-schemas\generator] executing: autorest-beta.cmd --version=3.0.6274 --use=@autorest/azureresourceschema@3.0.79 --azureresourceschema --output-folder=C:\Users\parkuma\AppData\Local\Temp\n515lvzixvi --tag=all-api-versions --api-version=2019-12-20-privatepreview --title=none --pass-thru:subset-reducer C:\Users\parkuma\AppData\Local\Temp\schm_azspc\specification\arcvmware\resource-manager\readme.md
AutoRest code generation utility [cli version: 3.0.6187; node: v12.16.1, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\parkuma\.autorest\@autorest_core@3.0.6274\node_modules\@autorest\core\dist' (3.0.6274)
   Loading AutoRest extension '@autorest/azureresourceschema' (3.0.79->3.0.79)
[9.63 s] Generation Complete
================================================================================================================================
Filename: D:\azure-resource-manager-schemas\schemas\2019-12-20-privatepreview\Microsoft.VMware.json
Provider Namespace: Microsoft.VMware
API Version: 2019-12-20-privatepreview
Resource Types (Resource Group Scope):
- ArcZones
- ResourcePools
- VCenters
- VirtualMachines
- VirtualMachineTemplates
- VirtualNetworks
================================================================================================================================
```

### CODE REVIEW

**Comment by parveenchahal** [comment]
Once this is checked-in. Will it be available to consume immediately or there are any other steps left which needs to be completed before we can use this?

**Comment by anthony-c-martin** [comment]
As discussed offline, we only support schemas for publicly-released APIs. Please can you supply a link to this API in the public swagger repo (https://github.com/Azure/azure-rest-api-specs)?

If you've got publicly-available swagger specs, I strongly recommend onboarding to the autogeneration pipeline: https://github.com/Azure/azure-resource-manager-schemas/tree/master/generator#onboarding-teams-to-autogeneration-pipeline

@leni-msft FYI

**Comment by anthony-c-martin** [comment]
> Once this is checked-in. Will it be available to consume immediately or there are any other steps left which needs to be completed before we can use this?

It'll be picked up in the next AzureResourceManager release and deployed with that build, so there'll be a ~7 day delay before the schema is used for Export.

**Comment by apclouds** [comment]
Once you are in Public Preview we will add you to the autogen list for autogeneration of schemas.

**Pull request closed without merging**
