### PR TITLE
Adding the 2016-03-01 version for microsoft.insights

### PR DESCRIPTION
**Pull request by snehithm**
@asheniam FYI

### CODE REVIEW

**Comment by Tiano2017** [comment]
Please update schemas/2014-04-01-preview/deploymentTemplate.json and schemas/2015-01-01/deploymentTemplate.json.

**Comment by Tiano2017** [comment]
Please add test.

**Comment by snehithm** [comment]
@Tiano2017 added test and updated schemas/2015-01-01/deploymentTemplate.json. schemas/2014-04-01-preview/deploymentTemplate.json already has the resource type Microsoft.Insights/alertrules with api version 2014-04-01. Let me know if we need to make more changes.

**Comment by snehithm** [comment]
@Tiano2017  can you please merge this.

**Comment by Tiano2017** [comment]
@snehithm please note: 2014-04-01-preview/deploymentTemplate doesn't have the 2016-03-01 version of alertRules.

**Comment by snehithm** [comment]
@Tiano2017 please merge. Update 2014-04-01-preview as well.

**Pull request merged**
