### PR TITLE
BatchAI. Schema for 2018-03-01 is autogenerated

### PR DESCRIPTION
**Pull request by AlexanderYukhanov**

### CODE REVIEW

**Comment by Tiano2017** [comment]
please add tests for your new schema.

**Comment by AlexanderYukhanov** [comment]
Hi, do we need unit tests for autogenerated shema?

**Comment by Tiano2017** [comment]
Yes we still need some basic tests. AutoRest can have issues sometimes.

**Comment by AlexanderYukhanov** [comment]
Added unit tests

**Comment by AlexanderYukhanov** [comment]
ping-ping

**Pull request merged**
