### PR TITLE
Added 2018-09-01 version for Microsoft.IoTCentral

### PR DESCRIPTION
**Pull request by zzcodework**
Added 2018-09-01 version for Microsoft.IoTCentral

### CODE REVIEW

**Comment by zzcodework** [comment]
@Tiano2017 @emgarten @amrenbin

**Comment by emgarten** [comment]
LGTM :shipit:

**Comment by zzcodework** [comment]
@Tiano2017 Can you take a look at this PR and let me know if there's anything need to be changed please?

**Comment by zzcodework** [comment]
Add @r-delgadillo

**Comment by Tiano2017** [comment]
PR looks good to me.  I can merge it unless you need more review from your team.

**Comment by zzcodework** [comment]
@Tiano2017 , please help to merge this directly, thanks!

**Pull request merged**
