### PR TITLE
Streamanalytics updates

### PR DESCRIPTION
**Pull request by thbagley**
Adding necessary resources to resourceDefinitions. Tried my best to be consistent with other schemas in the folders.

### CODE REVIEW

**Comment by Tiano2017** [comment]
@thbagley is the change generated from swagger?

**Comment by thbagley** [comment]
No, but I did my best to match it with the other schemas. Anything in particular that needs fixing?

**Comment by Tiano2017** [comment]
I don't see anything specific that needs fixing. If the same change is not in  swagger, it might be overwritten later if someone generate it from swagger.

**Comment by thbagley** [comment]
Our team is aware that we're managing this without swagger, so we should be alright. Thanks for double-checking.

**Comment by Tiano2017** [comment]
Looks good. Will merge.

**Pull request merged**
